# Generated by Django 5.0 on 2023-12-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.CharField(max_length=150)),
                ('valor_prestamo', models.FloatField(verbose_name='Valor de cuotas')),
                ('fecha_inicio_descuento', models.DateTimeField(blank=True, null=True)),
                ('numero_cuotas', models.IntegerField(verbose_name='Numero de cuotas')),
                ('cuotas', models.IntegerField(verbose_name='Cuotas')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'ordering': ['-fecha_prestamo'],
            },
        ),
    ]
